### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by mtavano** [juanbrujo/numberToCLPFormater#2]
I really thin you must to update readme to explain how to use your lib the right way.

your are saying that we must to import your lib like if we had the code locally on our source and this could be confusing
As I mentioned on PR #1, I think the right way to import and use your lib is:

``` javascript
var number = require('numbertoclpformater').numberToCLPFormater;
// instead of
// var number = require('./numberToCLPFormater.js');

number(876142) ;
  // $876.142
```

or even you can use

``` javascript
var number = require('numbertoclpformater');
// instead of
// var number = require('./numberToCLPFormater.js');

number.numberToCLPFormater(876142) ;
  // $876.142
```

On this last case maybe you should to explain that we're importing(or you're exporting) an object instead a function

**Comment by juanbrujo** [comment]
Done, updated as requested.
